// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketWrapper.proto

package protobuf.proto;

public interface WebsocketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kcwiki.msgtransfer.protobuf.Websocket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kcwiki.msgtransfer.protobuf.Websocket.ProtoType proto_type = 1;</code>
   */
  int getProtoTypeValue();
  /**
   * <code>.kcwiki.msgtransfer.protobuf.Websocket.ProtoType proto_type = 1;</code>
   */
  protobuf.proto.Websocket.ProtoType getProtoType();

  /**
   * <code>.kcwiki.msgtransfer.protobuf.Websocket.ProtoCode proto_code = 2;</code>
   */
  int getProtoCodeValue();
  /**
   * <code>.kcwiki.msgtransfer.protobuf.Websocket.ProtoCode proto_code = 2;</code>
   */
  protobuf.proto.Websocket.ProtoCode getProtoCode();

  /**
   * <code>string proto_module = 3;</code>
   */
  java.lang.String getProtoModule();
  /**
   * <code>string proto_module = 3;</code>
   */
  com.google.protobuf.ByteString
      getProtoModuleBytes();

  /**
   * <code>bytes proto_payload = 4;</code>
   */
  com.google.protobuf.ByteString getProtoPayload();

  /**
   * <code>int64 timestamp = 5;</code>
   */
  long getTimestamp();

  /**
   * <code>string sign = 6;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 6;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
