// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XTrafficWrapper.proto

package protobuf.proto;

/**
 * Protobuf type {@code kcwiki.msgtransfer.protobuf.XTrafficProto}
 */
public  final class XTrafficProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kcwiki.msgtransfer.protobuf.XTrafficProto)
    XTrafficProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use XTrafficProto.newBuilder() to construct.
  private XTrafficProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private XTrafficProto() {
    protoType_ = 0;
    protoCode_ = 0;
    protoModule_ = "";
    protoPayload_ = com.google.protobuf.ByteString.EMPTY;
    protoSender_ = "";
    protoRecipient_ = "";
    sign_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private XTrafficProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            protoType_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            protoCode_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            protoModule_ = s;
            break;
          }
          case 34: {

            protoPayload_ = input.readBytes();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            protoSender_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            protoRecipient_ = s;
            break;
          }
          case 56: {

            timestamp_ = input.readInt64();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            sign_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.proto.XTraffic.internal_static_kcwiki_msgtransfer_protobuf_XTrafficProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.proto.XTraffic.internal_static_kcwiki_msgtransfer_protobuf_XTrafficProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.proto.XTrafficProto.class, protobuf.proto.XTrafficProto.Builder.class);
  }

  /**
   * Protobuf enum {@code kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType}
   */
  public enum ProtoType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYSTEM = 0;</code>
     */
    SYSTEM(0),
    /**
     * <code>NON_SYSTEM = 1;</code>
     */
    NON_SYSTEM(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SYSTEM = 0;</code>
     */
    public static final int SYSTEM_VALUE = 0;
    /**
     * <code>NON_SYSTEM = 1;</code>
     */
    public static final int NON_SYSTEM_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtoType valueOf(int value) {
      return forNumber(value);
    }

    public static ProtoType forNumber(int value) {
      switch (value) {
        case 0: return SYSTEM;
        case 1: return NON_SYSTEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtoType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoType>() {
            public ProtoType findValueByNumber(int number) {
              return ProtoType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.proto.XTrafficProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtoType[] VALUES = values();

    public static ProtoType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtoType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType)
  }

  /**
   * Protobuf enum {@code kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode}
   */
  public enum ProtoCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FAILURE = 0;</code>
     */
    FAILURE(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>ERROR = 2;</code>
     */
    ERROR(2),
    /**
     * <code>UNKNOWN = 3;</code>
     */
    UNKNOWN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FAILURE = 0;</code>
     */
    public static final int FAILURE_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>ERROR = 2;</code>
     */
    public static final int ERROR_VALUE = 2;
    /**
     * <code>UNKNOWN = 3;</code>
     */
    public static final int UNKNOWN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtoCode valueOf(int value) {
      return forNumber(value);
    }

    public static ProtoCode forNumber(int value) {
      switch (value) {
        case 0: return FAILURE;
        case 1: return SUCCESS;
        case 2: return ERROR;
        case 3: return UNKNOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtoCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoCode>() {
            public ProtoCode findValueByNumber(int number) {
              return ProtoCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.proto.XTrafficProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final ProtoCode[] VALUES = values();

    public static ProtoCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtoCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode)
  }

  public static final int PROTO_TYPE_FIELD_NUMBER = 1;
  private int protoType_;
  /**
   * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType proto_type = 1;</code>
   */
  public int getProtoTypeValue() {
    return protoType_;
  }
  /**
   * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType proto_type = 1;</code>
   */
  public protobuf.proto.XTrafficProto.ProtoType getProtoType() {
    @SuppressWarnings("deprecation")
    protobuf.proto.XTrafficProto.ProtoType result = protobuf.proto.XTrafficProto.ProtoType.valueOf(protoType_);
    return result == null ? protobuf.proto.XTrafficProto.ProtoType.UNRECOGNIZED : result;
  }

  public static final int PROTO_CODE_FIELD_NUMBER = 2;
  private int protoCode_;
  /**
   * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode proto_code = 2;</code>
   */
  public int getProtoCodeValue() {
    return protoCode_;
  }
  /**
   * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode proto_code = 2;</code>
   */
  public protobuf.proto.XTrafficProto.ProtoCode getProtoCode() {
    @SuppressWarnings("deprecation")
    protobuf.proto.XTrafficProto.ProtoCode result = protobuf.proto.XTrafficProto.ProtoCode.valueOf(protoCode_);
    return result == null ? protobuf.proto.XTrafficProto.ProtoCode.UNRECOGNIZED : result;
  }

  public static final int PROTO_MODULE_FIELD_NUMBER = 3;
  private volatile java.lang.Object protoModule_;
  /**
   * <code>string proto_module = 3;</code>
   */
  public java.lang.String getProtoModule() {
    java.lang.Object ref = protoModule_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protoModule_ = s;
      return s;
    }
  }
  /**
   * <code>string proto_module = 3;</code>
   */
  public com.google.protobuf.ByteString
      getProtoModuleBytes() {
    java.lang.Object ref = protoModule_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protoModule_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTO_PAYLOAD_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString protoPayload_;
  /**
   * <code>bytes proto_payload = 4;</code>
   */
  public com.google.protobuf.ByteString getProtoPayload() {
    return protoPayload_;
  }

  public static final int PROTO_SENDER_FIELD_NUMBER = 5;
  private volatile java.lang.Object protoSender_;
  /**
   * <code>string proto_sender = 5;</code>
   */
  public java.lang.String getProtoSender() {
    java.lang.Object ref = protoSender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protoSender_ = s;
      return s;
    }
  }
  /**
   * <code>string proto_sender = 5;</code>
   */
  public com.google.protobuf.ByteString
      getProtoSenderBytes() {
    java.lang.Object ref = protoSender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protoSender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTO_RECIPIENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object protoRecipient_;
  /**
   * <code>string proto_recipient = 6;</code>
   */
  public java.lang.String getProtoRecipient() {
    java.lang.Object ref = protoRecipient_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protoRecipient_ = s;
      return s;
    }
  }
  /**
   * <code>string proto_recipient = 6;</code>
   */
  public com.google.protobuf.ByteString
      getProtoRecipientBytes() {
    java.lang.Object ref = protoRecipient_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protoRecipient_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 7;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int SIGN_FIELD_NUMBER = 8;
  private volatile java.lang.Object sign_;
  /**
   * <code>string sign = 8;</code>
   */
  public java.lang.String getSign() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sign_ = s;
      return s;
    }
  }
  /**
   * <code>string sign = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (protoType_ != protobuf.proto.XTrafficProto.ProtoType.SYSTEM.getNumber()) {
      output.writeEnum(1, protoType_);
    }
    if (protoCode_ != protobuf.proto.XTrafficProto.ProtoCode.FAILURE.getNumber()) {
      output.writeEnum(2, protoCode_);
    }
    if (!getProtoModuleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, protoModule_);
    }
    if (!protoPayload_.isEmpty()) {
      output.writeBytes(4, protoPayload_);
    }
    if (!getProtoSenderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, protoSender_);
    }
    if (!getProtoRecipientBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, protoRecipient_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (!getSignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sign_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (protoType_ != protobuf.proto.XTrafficProto.ProtoType.SYSTEM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, protoType_);
    }
    if (protoCode_ != protobuf.proto.XTrafficProto.ProtoCode.FAILURE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, protoCode_);
    }
    if (!getProtoModuleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, protoModule_);
    }
    if (!protoPayload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, protoPayload_);
    }
    if (!getProtoSenderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, protoSender_);
    }
    if (!getProtoRecipientBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, protoRecipient_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (!getSignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sign_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.proto.XTrafficProto)) {
      return super.equals(obj);
    }
    protobuf.proto.XTrafficProto other = (protobuf.proto.XTrafficProto) obj;

    if (protoType_ != other.protoType_) return false;
    if (protoCode_ != other.protoCode_) return false;
    if (!getProtoModule()
        .equals(other.getProtoModule())) return false;
    if (!getProtoPayload()
        .equals(other.getProtoPayload())) return false;
    if (!getProtoSender()
        .equals(other.getProtoSender())) return false;
    if (!getProtoRecipient()
        .equals(other.getProtoRecipient())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getSign()
        .equals(other.getSign())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTO_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + protoType_;
    hash = (37 * hash) + PROTO_CODE_FIELD_NUMBER;
    hash = (53 * hash) + protoCode_;
    hash = (37 * hash) + PROTO_MODULE_FIELD_NUMBER;
    hash = (53 * hash) + getProtoModule().hashCode();
    hash = (37 * hash) + PROTO_PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getProtoPayload().hashCode();
    hash = (37 * hash) + PROTO_SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getProtoSender().hashCode();
    hash = (37 * hash) + PROTO_RECIPIENT_FIELD_NUMBER;
    hash = (53 * hash) + getProtoRecipient().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.proto.XTrafficProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.XTrafficProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.XTrafficProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.XTrafficProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.XTrafficProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.XTrafficProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.XTrafficProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.XTrafficProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.XTrafficProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.proto.XTrafficProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.XTrafficProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.XTrafficProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.proto.XTrafficProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kcwiki.msgtransfer.protobuf.XTrafficProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kcwiki.msgtransfer.protobuf.XTrafficProto)
      protobuf.proto.XTrafficProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.proto.XTraffic.internal_static_kcwiki_msgtransfer_protobuf_XTrafficProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.proto.XTraffic.internal_static_kcwiki_msgtransfer_protobuf_XTrafficProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.proto.XTrafficProto.class, protobuf.proto.XTrafficProto.Builder.class);
    }

    // Construct using protobuf.proto.XTrafficProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      protoType_ = 0;

      protoCode_ = 0;

      protoModule_ = "";

      protoPayload_ = com.google.protobuf.ByteString.EMPTY;

      protoSender_ = "";

      protoRecipient_ = "";

      timestamp_ = 0L;

      sign_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.proto.XTraffic.internal_static_kcwiki_msgtransfer_protobuf_XTrafficProto_descriptor;
    }

    @java.lang.Override
    public protobuf.proto.XTrafficProto getDefaultInstanceForType() {
      return protobuf.proto.XTrafficProto.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.proto.XTrafficProto build() {
      protobuf.proto.XTrafficProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.proto.XTrafficProto buildPartial() {
      protobuf.proto.XTrafficProto result = new protobuf.proto.XTrafficProto(this);
      result.protoType_ = protoType_;
      result.protoCode_ = protoCode_;
      result.protoModule_ = protoModule_;
      result.protoPayload_ = protoPayload_;
      result.protoSender_ = protoSender_;
      result.protoRecipient_ = protoRecipient_;
      result.timestamp_ = timestamp_;
      result.sign_ = sign_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.proto.XTrafficProto) {
        return mergeFrom((protobuf.proto.XTrafficProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.proto.XTrafficProto other) {
      if (other == protobuf.proto.XTrafficProto.getDefaultInstance()) return this;
      if (other.protoType_ != 0) {
        setProtoTypeValue(other.getProtoTypeValue());
      }
      if (other.protoCode_ != 0) {
        setProtoCodeValue(other.getProtoCodeValue());
      }
      if (!other.getProtoModule().isEmpty()) {
        protoModule_ = other.protoModule_;
        onChanged();
      }
      if (other.getProtoPayload() != com.google.protobuf.ByteString.EMPTY) {
        setProtoPayload(other.getProtoPayload());
      }
      if (!other.getProtoSender().isEmpty()) {
        protoSender_ = other.protoSender_;
        onChanged();
      }
      if (!other.getProtoRecipient().isEmpty()) {
        protoRecipient_ = other.protoRecipient_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getSign().isEmpty()) {
        sign_ = other.sign_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.proto.XTrafficProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.proto.XTrafficProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int protoType_ = 0;
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType proto_type = 1;</code>
     */
    public int getProtoTypeValue() {
      return protoType_;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType proto_type = 1;</code>
     */
    public Builder setProtoTypeValue(int value) {
      protoType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType proto_type = 1;</code>
     */
    public protobuf.proto.XTrafficProto.ProtoType getProtoType() {
      @SuppressWarnings("deprecation")
      protobuf.proto.XTrafficProto.ProtoType result = protobuf.proto.XTrafficProto.ProtoType.valueOf(protoType_);
      return result == null ? protobuf.proto.XTrafficProto.ProtoType.UNRECOGNIZED : result;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType proto_type = 1;</code>
     */
    public Builder setProtoType(protobuf.proto.XTrafficProto.ProtoType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      protoType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoType proto_type = 1;</code>
     */
    public Builder clearProtoType() {
      
      protoType_ = 0;
      onChanged();
      return this;
    }

    private int protoCode_ = 0;
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode proto_code = 2;</code>
     */
    public int getProtoCodeValue() {
      return protoCode_;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode proto_code = 2;</code>
     */
    public Builder setProtoCodeValue(int value) {
      protoCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode proto_code = 2;</code>
     */
    public protobuf.proto.XTrafficProto.ProtoCode getProtoCode() {
      @SuppressWarnings("deprecation")
      protobuf.proto.XTrafficProto.ProtoCode result = protobuf.proto.XTrafficProto.ProtoCode.valueOf(protoCode_);
      return result == null ? protobuf.proto.XTrafficProto.ProtoCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode proto_code = 2;</code>
     */
    public Builder setProtoCode(protobuf.proto.XTrafficProto.ProtoCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      protoCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kcwiki.msgtransfer.protobuf.XTrafficProto.ProtoCode proto_code = 2;</code>
     */
    public Builder clearProtoCode() {
      
      protoCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object protoModule_ = "";
    /**
     * <code>string proto_module = 3;</code>
     */
    public java.lang.String getProtoModule() {
      java.lang.Object ref = protoModule_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protoModule_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proto_module = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProtoModuleBytes() {
      java.lang.Object ref = protoModule_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protoModule_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proto_module = 3;</code>
     */
    public Builder setProtoModule(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protoModule_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proto_module = 3;</code>
     */
    public Builder clearProtoModule() {
      
      protoModule_ = getDefaultInstance().getProtoModule();
      onChanged();
      return this;
    }
    /**
     * <code>string proto_module = 3;</code>
     */
    public Builder setProtoModuleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protoModule_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString protoPayload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes proto_payload = 4;</code>
     */
    public com.google.protobuf.ByteString getProtoPayload() {
      return protoPayload_;
    }
    /**
     * <code>bytes proto_payload = 4;</code>
     */
    public Builder setProtoPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protoPayload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes proto_payload = 4;</code>
     */
    public Builder clearProtoPayload() {
      
      protoPayload_ = getDefaultInstance().getProtoPayload();
      onChanged();
      return this;
    }

    private java.lang.Object protoSender_ = "";
    /**
     * <code>string proto_sender = 5;</code>
     */
    public java.lang.String getProtoSender() {
      java.lang.Object ref = protoSender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protoSender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proto_sender = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProtoSenderBytes() {
      java.lang.Object ref = protoSender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protoSender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proto_sender = 5;</code>
     */
    public Builder setProtoSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protoSender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proto_sender = 5;</code>
     */
    public Builder clearProtoSender() {
      
      protoSender_ = getDefaultInstance().getProtoSender();
      onChanged();
      return this;
    }
    /**
     * <code>string proto_sender = 5;</code>
     */
    public Builder setProtoSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protoSender_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object protoRecipient_ = "";
    /**
     * <code>string proto_recipient = 6;</code>
     */
    public java.lang.String getProtoRecipient() {
      java.lang.Object ref = protoRecipient_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protoRecipient_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proto_recipient = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProtoRecipientBytes() {
      java.lang.Object ref = protoRecipient_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protoRecipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proto_recipient = 6;</code>
     */
    public Builder setProtoRecipient(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protoRecipient_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proto_recipient = 6;</code>
     */
    public Builder clearProtoRecipient() {
      
      protoRecipient_ = getDefaultInstance().getProtoRecipient();
      onChanged();
      return this;
    }
    /**
     * <code>string proto_recipient = 6;</code>
     */
    public Builder setProtoRecipientBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protoRecipient_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object sign_ = "";
    /**
     * <code>string sign = 8;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sign = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sign = 8;</code>
     */
    public Builder setSign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 8;</code>
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 8;</code>
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sign_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kcwiki.msgtransfer.protobuf.XTrafficProto)
  }

  // @@protoc_insertion_point(class_scope:kcwiki.msgtransfer.protobuf.XTrafficProto)
  private static final protobuf.proto.XTrafficProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.proto.XTrafficProto();
  }

  public static protobuf.proto.XTrafficProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<XTrafficProto>
      PARSER = new com.google.protobuf.AbstractParser<XTrafficProto>() {
    @java.lang.Override
    public XTrafficProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new XTrafficProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<XTrafficProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<XTrafficProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.proto.XTrafficProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

